In [1]:
import pandas as pd
import seaborn as sns
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('C:\\Users\\elitebook 840\\Desktop\\Data_for_UCI_named.csv')

In [3]:
data.describe()

tau1          tau2          tau3          tau4            p1  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean       5.250000      5.250001      5.250004      5.249997      3.750000   
std        2.742548      2.742549      2.742549      2.742556      0.752160   
min        0.500793      0.500141      0.500788      0.500473      1.582590   
25%        2.874892      2.875140      2.875522      2.874950      3.218300   
50%        5.250004      5.249981      5.249979      5.249734      3.751025   
75%        7.624690      7.624893      7.624948      7.624838      4.282420   
max        9.999469      9.999837      9.999450      9.999443      5.864418   

                 p2            p3            p4            g1            g2  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -1.250000     -1.250000     -1.250000      0.525000      0.525000   
std        0.433035      0.433035      0.433035      0.274256      0.274255   
min       -1.999891     -1.999945     -1.999926      0.050009      0.050053   
25%       -1.624901     -1.625025     -1.624960      0.287521      0.287552   
50%       -1.249966     -1.249974     -1.250007      0.525009      0.525003   
75%       -0.874977     -0.875043     -0.875065      0.762435      0.762490   
max       -0.500108     -0.500072     -0.500025      0.999937      0.999944   

                 g3            g4          stab  
count  10000.000000  10000.000000  10000.000000  
mean       0.525000      0.525000      0.015731  
std        0.274255      0.274255      0.036919  
min        0.050054      0.050028     -0.080760  
25%        0.287514      0.287494     -0.015557  
50%        0.525015      0.525002      0.017142  
75%        0.762440      0.762433      0.044878  
max        0.999982      0.999930      0.109403

In [4]:
data['stab'].value_counts()
data.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [5]:
data['stabf'].value_counts()
data.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [6]:
data.drop(['stab'],axis=1,inplace=True)

In [7]:
data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [8]:
data.stabf.value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [9]:
data_unstable = data[data.stabf=='unstable'].sample(6380)
data_stable = data[data.stabf=='stable'].sample(3620)
data_data = data_unstable.append(data_stable)

In [10]:
import sklearn.utils
data_data = sklearn.utils.shuffle(data_data)
data_data = data_data.reset_index(drop=True)
data_data.shape
data_data.stabf.value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [11]:
#check the data type of the dataset
data_data.dtypes

tau1     float64
tau2     float64
tau3     float64
tau4     float64
p1       float64
p2       float64
p3       float64
p4       float64
g1       float64
g2       float64
g3       float64
g4       float64
stabf     object
dtype: object

In [12]:
x = data_data.drop(columns='stabf')
y = data_data['stabf']

In [13]:
#To split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
y_train.value_counts()

unstable    5102
stable      2898
Name: stabf, dtype: int64

In [14]:
#To train Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

forest = RandomForestClassifier(random_state=1)
forest.fit(x_train, y_train)
y_pred = forest.predict(x_test)

In [15]:
print(classification_report(y_test, y_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9074    0.8684    0.8875       722
    unstable     0.9274    0.9499    0.9385      1278

    accuracy                         0.9205      2000
   macro avg     0.9174    0.9092    0.9130      2000
weighted avg     0.9202    0.9205    0.9201      2000



In [16]:
print(confusion_matrix(y_test, y_pred))

[[ 627   95]
 [  64 1214]]


In [17]:
print(accuracy_score(y_test, y_pred).round(4))

0.9205


In [18]:
#extra tree classifier 

from sklearn.ensemble import ExtraTreesClassifier

tree = ExtraTreesClassifier(random_state=1)
tree.fit(x_train, y_train)
tree_pred = tree.predict(x_test)

In [19]:
print(classification_report(y_test, y_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9074    0.8684    0.8875       722
    unstable     0.9274    0.9499    0.9385      1278

    accuracy                         0.9205      2000
   macro avg     0.9174    0.9092    0.9130      2000
weighted avg     0.9202    0.9205    0.9201      2000



In [20]:
print(confusion_matrix(y_test, y_pred))

[[ 627   95]
 [  64 1214]]


In [23]:
print(accuracy_score(y_test, y_pred).round(4))

0.9205


In [24]:
#parameters to use 
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'squrt', 'log2', None]
hyperparameter_grid = {'n_estimators': n_estimators,
                     'min_samples_leaf': min_samples_leaf,
                     'min_samples_split': min_samples_split,
                     'max_features': max_features}

In [25]:
from sklearn.model_selection import RandomizedSearchCV

tree = ExtraTreesClassifier(random_state=1)
rscv = RandomizedSearchCV(tree, hyperparameter_grid, random_state=1)
rscv.fit(x_train, y_train)

C:\Users\elitebook 840\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\elitebook 840\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\elitebook 840\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    for i, t in enumerate(trees))
  File "C:\Users\elitebook 840\anaconda3\lib\site-packages\joblib\parallel.py", line 1004, in __call__
    if self.dispatch_one_batch(iterator):
  File "C:\Users\elitebook 840\anaconda3\lib\site-packages\joblib\parallel.py", line 835, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\elitebook 840\anaconda3\lib\site-packages\joblib\parallel.py", line 754, in _dispatch
    job = self._backend.apply_async(

RandomizedSearchCV(estimator=ExtraTreesClassifier(random_state=1),
                   param_distributions={'max_features': ['auto', 'squrt',
                                                         'log2', None],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 3, 5, 7, 9],
                                        'n_estimators': [50, 100, 300, 500,
                                                         1000]},
                   random_state=1)

In [26]:
print(classification_report(y_test, y_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9074    0.8684    0.8875       722
    unstable     0.9274    0.9499    0.9385      1278

    accuracy                         0.9205      2000
   macro avg     0.9174    0.9092    0.9130      2000
weighted avg     0.9202    0.9205    0.9201      2000



In [27]:
print(confusion_matrix(y_test, y_pred))

[[ 627   95]
 [  64 1214]]


In [29]:
print(accuracy_score(y_test, y_pred).round(4))

0.9205


In [30]:
#checking the best estimator for the model
rscv.best_estimator_

ExtraTreesClassifier(max_features=None, min_samples_leaf=8, n_estimators=1000,
                     random_state=1)

In [31]:
#checking the best parameter for the model
rscv.best_params_.values()

dict_values([1000, 2, 8, None])

In [32]:
#testing two xgboost classifier
#xgboost with random forest
from xgboost import XGBRFClassifier
extreme = XGBRFClassifier(random_state=1)
extreme.fit(x_train, y_train)
extreme_pred = extreme.predict(x_test)

In [33]:
#classification report 
print(classification_report(y_test, extreme_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.8465    0.5499    0.6667       722
    unstable     0.7877    0.9437    0.8587      1278

    accuracy                         0.8015      2000
   macro avg     0.8171    0.7468    0.7627      2000
weighted avg     0.8089    0.8015    0.7894      2000



In [34]:
print(confusion_matrix(y_test, y_pred))

[[ 627   95]
 [  64 1214]]


In [36]:
print(accuracy_score(y_test, y_pred).round(4))

0.9205


In [37]:
#xgboost using gradient boosting 
from xgboost import XGBClassifier
extreme1 = XGBClassifier(random_state=1)
extreme1.fit(x_train, y_train)
extreme1_pred = extreme1.predict(x_test)

In [38]:
#classification report 
print(classification_report(y_test, extreme1_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9132    0.8449    0.8777       722
    unstable     0.9159    0.9546    0.9349      1278

    accuracy                         0.9150      2000
   macro avg     0.9145    0.8997    0.9063      2000
weighted avg     0.9149    0.9150    0.9142      2000



In [39]:
print(confusion_matrix(y_test, y_pred))

[[ 627   95]
 [  64 1214]]


In [40]:
print(accuracy_score(y_test, y_pred).round(4))

0.9205


In [41]:
#lightgbm
from lightgbm import LGBMClassifier
light = LGBMClassifier(random_state=1)
light.fit(x_train, y_train)
light_pred =light.predict(x_test)

In [42]:
#classification report 
print(classification_report(y_test, light_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9248    0.9030    0.9138       722
    unstable     0.9459    0.9585    0.9522      1278

    accuracy                         0.9385      2000
   macro avg     0.9354    0.9308    0.9330      2000
weighted avg     0.9383    0.9385    0.9383      2000



In [43]:
print(confusion_matrix(y_test, y_pred))

[[ 627   95]
 [  64 1214]]


In [50]:
print(accuracy_score(y_test, y_pred).round(4))

0.9205


In [51]:
#Another extra tree classifier 

from sklearn.ensemble import ExtraTreesClassifier

tree = ExtraTreesClassifier(random_state=1)
tree.fit(x_train, y_train)
tree_pred = tree.predict(x_test)

In [52]:
#classification report 
print(classification_report(y_test, light_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9248    0.9030    0.9138       722
    unstable     0.9459    0.9585    0.9522      1278

    accuracy                         0.9385      2000
   macro avg     0.9354    0.9308    0.9330      2000
weighted avg     0.9383    0.9385    0.9383      2000



In [53]:
print(accuracy_score(y_test, y_pred).round(4))

0.9205


In [58]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)
#returns
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True, intercept_scaling=1, l1_ratio=None, max_iter=100,
                  multi_class='auto', n_jobs=None, penalty= '12', random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                  warm_start=False)

LogisticRegression(penalty='12')

In [59]:
print(confusion_matrix(y_test, y_pred))

[[ 627   95]
 [  64 1214]]


In [60]:
#classification report 
print(classification_report(y_test, light_pred, digits=4))

              precision    recall  f1-score   support

      stable     0.9248    0.9030    0.9138       722
    unstable     0.9459    0.9585    0.9522      1278

    accuracy                         0.9385      2000
   macro avg     0.9354    0.9308    0.9330      2000
weighted avg     0.9383    0.9385    0.9383      2000

